### ISSUE TITLE
Recorded Video issue 

### ISSUE THREAD

**Issue by arbaajq4udev** [HBiSoft/HBRecorder#165] opened 2024-05-18 09:14 UTC
Recorded video showing black line lift and right on video

**Comment by AbdulWahab1539** [comment] 2024-05-21 10:42
Yes! It does it when you are not recording in 1080p resolution. I have tested on Samsung devices S10e & S22 Ultra

**Comment by HBiSoft** [comment] 2024-08-12 09:59
You have probably moved on from this by now. I tested on a Samsung S22 Ultra and was not able to reproduce it.

Please let me know how I can reproduce this (settings used and if it can be reproduced in the demo app).


With the info provided its impossible to figure out why this is happening.

Closing for now.

**Closed by HBiSoft** 2024-08-12 09:59 UTC
Labels: Need more info
