### ISSUE TITLE
video recording not starting in android Lollipop ?

### ISSUE THREAD

**Issue by chiragthummar** [HBiSoft/HBRecorder#33] opened 2020-09-22 11:23 UTC
it just gives simple error while start recording in it.

`HBRecorderOnError: 268435556`

**Comment by chiragthummar** [comment] 2020-09-22 11:24
on other version it works fine

**Comment by HBiSoft** [comment] 2020-09-22 11:35
Please see [Always fill in the issue template](https://github.com/HBiSoft/HBRecorder/issues/31)

**Comment by chiragthummar** [comment] 2020-09-22 11:38
but logcat not showing other log which i can post here.
it just give simply error above.

**Comment by HBiSoft** [comment] 2020-09-22 13:41
Does this happen using the demo application?
Do you start the recording from your application or a service?
Do you have any application open when starting the recording?

**Comment by chiragthummar** [comment] 2020-09-22 14:31
have used demo application which is provided in lib and starting recording from the service as given in example.
nothing changed. and also when i start app it just goes in ANR .

**Comment by chiragthummar** [comment] 2020-09-23 12:52
HBRecorder throwing error because of the directory is not created in emulator .

**Comment by HBiSoft** [comment] 2020-09-26 07:18
I have tested it on a physical device running lollipop and I can't reproduce this. I believe it could be related to the emulator. I'm closing the issue for now. If you can reproduce this on a physical device, please reopen the issue.

**Closed by HBiSoft** 2020-09-26 07:18 UTC
Labels: Device Specific, Emulator, No template
