### ISSUE TITLE
After upgrading to version 3.0.2 the project does not see the library

### ISSUE THREAD

**Issue by podolyanbogdan** [HBiSoft/HBRecorder#159] opened 2024-02-27 08:56 UTC
After upgrading to version 3.0.2 the project does not see the library

**Comment by alihamzaazhar** [comment] 2024-03-12 19:42
Same-issue!

**Comment by robrechtme** [comment] 2024-03-13 13:44
Duplicate of https://github.com/HBiSoft/HBRecorder/issues/158

**Comment by HBiSoft** [comment] 2024-03-14 05:38
Duplicate of #158

**Closed by HBiSoft** 2024-03-14 05:38 UTC
