### ISSUE TITLE
HBRecorderOnError error code 38 

### ISSUE THREAD

**Issue by akashappscale** [HBiSoft/HBRecorder#155] opened 2024-01-05 06:55 UTC
Before filing a bug:
-----------------------
HBRecorderOnError error code 38 

Some settings are not supported by your device

 devices OPPO CPH1725 
 
 
  implementation 'com.github.HBiSoft:HBRecorder:3.0.1'

**Comment by HBiSoft** [comment] 2024-01-05 07:28
It is impossible to know why you are getting this error without knowing how you implemented `HBRecorder`.

**Comment by akashappscale** [comment] 2024-01-05 07:31
> It is impossible to know why you are getting this error without knowing how you implemented `HBRecorder`.

https://github.com/HBiSoft/HBRecorder

**Comment by akashappscale** [comment] 2024-01-06 10:59
screen recorder not working 
OPPO CPH1819 

errorcode is 38

error is Some settings are not supported by your device

**Comment by HBiSoft** [comment] 2024-01-06 11:44
As I have already said in the issue you commented on yesterday: https://github.com/HBiSoft/HBRecorder/issues/70#issuecomment-1878178376
>You can make use of the `HBRecorderCodecInfo.java` class, as shown in the demo application, to check what settings and encoder are supported and then make the changes accordingly:

>https://github.com/HBiSoft/HBRecorder/blob/a8207fe6b05f0a7701516ad83e881403e491130b/app/src/main/java/com/hbisoft/hbrecorderexample/MainActivity.java#L137-L173

Without knowing what settings you have selected and without knowing how you have implemented the library into your application, I will not be able to help you!

`error code 38` Can be caused by a lot of things, but from the tests I have done:
https://github.com/HBiSoft/HBRecorder/blob/a8207fe6b05f0a7701516ad83e881403e491130b/hbrecorder/src/main/java/com/hbisoft/hbrecorder/ScreenRecordService.java#L302

</br>

I will be closing this issue **until you provide the above.**

**Closed by HBiSoft** 2024-01-06 11:44 UTC
Labels: Need more info
