### ISSUE TITLE
Stop application when start recording

### ISSUE THREAD

**Issue by MrNouri** [HBiSoft/HBRecorder#3] opened 2019-10-06 06:53 UTC
**Describe the bug**
When click on start button show me force close error

**Log**
```
java.lang.RuntimeException: Unable to start service com.hbisoft.hbrecorder.ScreenRecordService@dc8478b with Intent { cmp=com.hbisoft.hbrecorderexample/com.hbisoft.hbrecorder.ScreenRecordService (has extras) }: java.lang.IllegalStateException: failed to get surface
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3045)
        at android.app.ActivityThread.access$2200(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5530)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
     Caused by: java.lang.IllegalStateException: failed to get surface
        at android.media.MediaRecorder.getSurface(Native Method)
        at com.hbisoft.hbrecorder.ScreenRecordService.createVirtualDisplay(ScreenRecordService.java:226)
        at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:148)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
```

**HBRecorder version**
for example 1.0.1

**Device information**
- LG K430
- Android 6

**Comment by HBiSoft** [comment] 2019-10-06 07:07
Can you reproduce the crash in the demo application?

**Comment by MrNouri** [comment] 2019-10-06 07:16
Yes, i clone your project and after run application on LG K430 when click on start button (from your app) show me above error!

**Comment by HBiSoft** [comment] 2019-10-06 07:23
I think I know why it's happening. Can you download [this](https://play.google.com/store/apps/details?id=com.ellevsoft.mediacodecinfo&hl) application and check what video encoder your device supports for AVC (H264)?

**Comment by HBiSoft** [comment] 2019-10-06 07:27
If it does, you will see the following:

![Screenshot_20191006-092557_Media Codec Info](https://user-images.githubusercontent.com/35602540/66265731-871b8700-e81b-11e9-89d9-02076405eb86.jpg)

**Comment by MrNouri** [comment] 2019-10-06 07:55
In suggested app show me 4 AVC(H264)
Max resolutions **896*896** and **1920*1072** are supported ! ( **Encoder** )
Max resolutions **2048*2048** and **1920*1088** are not supported ! ( **Decoder** )

**Comment by HBiSoft** [comment] 2019-10-06 08:23
The only thing I can think of is the order at which the parameters are set could be incorrect. You said you cloned the project, can you try and change line 186-219 inside ScreenRecordService to the following:

MediaRecorder mediaRecorder = new MediaRecorder();


        if (isAudioEnabled) {
            mediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        }
        mediaRecorder.setVideoSource(MediaRecorder.VideoSource.SURFACE);
        mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
        if (isAudioEnabled) {
            mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
            mediaRecorder.setAudioEncodingBitRate(audioBitrate);
            mediaRecorder.setAudioSamplingRate(audioSamplingRate);
        }

        mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.DEFAULT);
        mediaRecorder.setOutputFile(path + "/" + name + ".mp4");
        mediaRecorder.setVideoSize(mScreenWidth, mScreenHeight);

        if (!isVideoHD) {
            mediaRecorder.setVideoEncodingBitRate(5000000);
            mediaRecorder.setVideoFrameRate(30);
            Log.e("info - ", String.valueOf(2 * mScreenWidth * mScreenHeight));
        } else {
            mediaRecorder.setVideoEncodingBitRate(5 * mScreenWidth * mScreenHeight);
            mediaRecorder.setVideoFrameRate(60); //after setVideoSource(), setOutFormat()
        }


        try {
            mediaRecorder.prepare();
        } catch (IllegalStateException | IOException e) {
            Log.e(TAG, "createMediaRecorder: e = " + e.toString());
        }

**Comment by MrNouri** [comment] 2019-10-06 09:15
Thanks dear for fix above error.
I paste your code in line 189-219 fix above error.
But after finished recorder and play video show me with below effect!
https://i.stack.imgur.com/uGsNM.png
**Distortion** in recorded video

**Comment by HBiSoft** [comment] 2019-10-06 10:38
Are you recording HD or SD video?

**Comment by MrNouri** [comment] 2019-10-06 10:52
HD . can you fix it?

**Comment by MrNouri** [comment] 2019-10-06 10:54
I check SD and again show video above effect!

**Comment by HBiSoft** [comment] 2019-10-06 11:41
Try removing the following in ScreenRecordingService:

    if (!isVideoHD) {
        mediaRecorder.setVideoEncodingBitRate(5000000);
        mediaRecorder.setVideoFrameRate(30);
    } else {
        mediaRecorder.setVideoEncodingBitRate(5 * mScreenWidth * mScreenHeight);
        mediaRecorder.setVideoFrameRate(60); //after setVideoSource(), setOutFormat()
    }

**Comment by MrNouri** [comment] 2019-10-06 11:52
I try this. not fix and video played such as above!

**Comment by HBiSoft** [comment] 2019-10-06 12:09
I see you have Az Screen Recorder installed on your device, I assume it's working as you want. Please tell me what your settings are in Az?

**Comment by MrNouri** [comment] 2019-10-06 12:11
Yes installed AzRecorder app, I didn't change the default changes

**Comment by HBiSoft** [comment] 2019-10-06 16:26
I will update the library tomorrow and provide more control over the settings..

**Comment by MrNouri** [comment] 2019-10-07 06:10
Thanks dear, i will wait you

**Comment by HBiSoft** [comment] 2019-10-07 06:18
Before I update the library, can you try changing:

    mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);

to

    mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);

in ScreenRecordingService.

**Comment by MrNouri** [comment] 2019-10-07 06:36
I try your new code, but not work again :(

**Comment by MrNouri** [comment] 2019-10-07 06:40
I uploaded recorded video , please see this : [http://uupload.ir/view/b43_sd2019-10-07-10-07-41.mp4/](url)

**Comment by HBiSoft** [comment] 2019-10-07 13:12
I just started working on upgrading the demo project. I can not reproduce this issue on my devices, you will have to wait until I release the new version later today and then test all the available parameters to find the issue.

**Comment by HBiSoft** [comment] 2019-10-09 14:56
Sorry for the wait. I have just updated the library. Please try different settings in the demo application and check if you can find a setting that works for your device. Please let me know.

**Comment by HBiSoft** [comment] 2019-10-10 07:08
The only thing that I can think of besides what we have already tried is to enable/disable hardware acceleration.

You can do this by adding the following in your app level gradle file:

    <application android:hardwareAccelerated="true" ...>

If that doesn't work, go into Az screen recorder and send me the settings that are selected.

**Comment by HBiSoft** [comment] 2019-10-11 06:53
Did you try it?

**Comment by MrNouri** [comment] 2019-10-13 05:10
yes my friend, but again not work me!!!

**Comment by HBiSoft** [comment] 2019-10-13 05:16
Read the last part of my comment above `If that doesn't work, go into Az screen recorder and send me the settings that are selected.`

**Comment by HBiSoft** [comment] 2019-10-14 10:02
I'm closing this issue since there is nothing that I can do about this without having this device to test with. The issue clearly has something to do with the selected codec and the parameters that are passed to it. I will wait and see if someone else opens a similar issue in the future.

**Closed by HBiSoft** 2019-10-14 10:02 UTC
Labels: Device Specific

**Comment by HBiSoft** [comment] 2019-10-29 08:20
@MrNouri Were you able to find out what was wrong?

**Comment by MrNouri** [comment] 2019-10-29 13:12
Sorry for the delay in answer.
Unfortunately, I couldn't find the problem.I think they use another way to record video

**Comment by HBiSoft** [comment] 2019-10-29 13:49
There is no other way unless your device is rooted. I'm 100% sure that it is caused by passing the wrong values to `MediaRecorder`. If I had your device I could have done tests myself.

If you really want to find the cause, open AZ Screen recorder's settings and modify `ScreenRecordService.java` to match it.

I have asked you multiple times to provide me the options that are set in AZScreenRecorder..:sweat:

**Comment by HBiSoft** [comment] 2020-01-15 04:43
@MrNouri 
I thought that I would let you know that I have improved error handling. With this release, we will at least know if `MediaRecorder` prepares successfully. I also changed the order of when `MediaRecorder` gets initialized.

If you still have not resolved this issue, please try the new release.

**Comment by MrNouri** [comment] 2020-01-16 18:02
Thanks my dear friend.<br>
I'll test in two days and say to you the result

**Comment by HBiSoft** [comment] 2020-01-21 03:43
@MrNouri 
Did you test it?

**Comment by HBiSoft** [comment] 2020-01-21 11:12
@MrNouri 
Ok, but what did the log say?

**Comment by MrNouri** [comment] 2020-01-23 10:45
Yes, but how can i send you? 
How do I get the log for you?

**Comment by HBiSoft** [comment] 2020-01-23 10:51
@MrNouri 

>How do I get the log for you?

What do you mean? You send it the same way as you did above?

**Comment by HBiSoft** [comment] 2020-02-21 18:51
This issue is fixed in `0.1.6`. We had the same happen in #6 and was able to find/fix the issue.

**Comment by webix-209** [comment] 2020-12-28 09:34
E/HBRecorderOnError: 268435556

every time this error show how to fix it in version 29?

**Comment by illescasDaniel** [comment] 2021-11-02 11:42
Setting "H264" as video encoder worked for me: recorder.setVideoEncoder("H264")
