### ISSUE TITLE
Error and Complete Listener not triggered 

### ISSUE THREAD

**Issue by shehroz76** [HBiSoft/HBRecorder#7] opened 2020-02-24 18:57 UTC
Error and Complete Listener not triggered 
And let me know how to save the file in gallery?

**Comment by HBiSoft** [comment] 2020-02-25 03:06
Closing this issue. You can open a new issue and fill in the issue form providing the logs, device model, steps to reproduce etc.

As the question is now, it's impossible to figure out what the issue is.

**Closed by HBiSoft** 2020-02-25 03:06 UTC
