### ISSUE TITLE
HBRecorderOnError  see log

### ISSUE THREAD

**Issue by sutanurath** [HBiSoft/HBRecorder#34] opened 2020-10-01 14:00 UTC
HBRecorderOnError: 268435556

When i pressing start button its automatically stop and toast message is showing HBRecorderOnError  see log and log error is 268435556. I tested sample app but same error. In HBRecorder class there is a exception on  startService method. My device is 1820 and version 8.1.0 API level 27

**Comment by HBiSoft** [comment] 2020-10-02 04:19
Please make sure that the directory is created. The last issue that was closed had the exact same error.

**Comment by saqibahsan1** [comment] 2020-10-02 06:50
directory was created , but the same issue occurred  on my device ( Redmi note 8 pro ) android  version 10, error  code 268435556

**Comment by sutanurath** [comment] 2020-10-02 14:24
Directory was created. And mp4 file also generated with small size. but same issue still there. HBRecorderOnError see log and log with same error code

**Comment by HBiSoft** [comment] 2020-10-02 15:05
Unfortunately,  `MediaRecorder` errors are not very informative. All I can do from my side is to provide suggestions you can try.

- Make sure there are no applications open which are using the mic
- Try disabling the audio
- Try selecting a different video encoder
- Try saving the video to your application directory instead of `Movies` or `DCIM`
- Try reducing the video dimensions using `hbRecorder.setScreenDimensions(HeightInPx, WidthInPx);`

I've also seen that [some people say](https://stackoverflow.com/questions/40616466/mediarecorder-stop-failed-1007) that this occurs when stoping the recording immediately after starting it (Stopping before frames are written).

**Comment by sutanurath** [comment] 2020-10-03 15:51
Default video encoder not working. only h264 is working

**Comment by HBiSoft** [comment] 2020-10-04 05:53
@sutanurath 
Please try and set the `Output Format` and `Video encoder` to `DEFAULT` and let me know if it works.

I see that I have set the default format in the library to `MPEG_4`. So it could be that your device is selecting `H263` as it's default encoder and `MPEG_4` for the format, which might be causing the issue.

**Comment by sutanurath** [comment] 2020-10-04 09:26
Thank a lot for your support. Fixed the issue.

**Comment by HBiSoft** [comment] 2020-10-04 09:33
@sutanurath 
What did you do to fix it?

**Comment by sutanurath** [comment] 2020-10-04 12:54
Its device problem where i tested last time. now  i am using another device, working fine. with all default settings.

**Comment by HBiSoft** [comment] 2020-10-04 18:44
@saqibahsan1 
Are you still getting this error?

**Comment by sutanurath** [comment] 2020-10-05 05:33
Yes still getting this error on that device. Device is Vivo 1820 Version 8.1.0. Only h264 encode working.

**Comment by HBiSoft** [comment] 2020-10-05 05:35
Did you try what I asked above?

>Please try and set the Output Format and Video encoder to DEFAULT and let me know if it works.

**Comment by saqibahsan1** [comment] 2020-10-05 06:17
Default video encoder not working. only h264 is working

**Comment by HBiSoft** [comment] 2020-10-05 06:22
Did you try and set the video encoder AND the output format to default?

**Comment by HBiSoft** [comment] 2020-10-05 07:19
If that also doesn't work, run the following and let me know what it returns:

```java
public void logAvailableVideoEncoders(){
    final int numCodecs = MediaCodecList.getCodecCount();
    for (int i = 0; i < numCodecs; i++) {
        final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
        if (!codecInfo.isEncoder()) { 
            continue;
        }
        final String[] types = codecInfo.getSupportedTypes();
        for (int j = 0; j < types.length; j++) {
            if (types[j].contains("video")){
                Log.e("Available Encoders", codecInfo.getName());
            }
        }
    }
}
```

**Comment by sutanurath** [comment] 2020-10-05 10:24
> 
> 
> @sutanurath
> Please try and set the `Output Format` and `Video encoder` to `DEFAULT` and let me know if it works.
> 
> I see that I have set the default format in the library to `MPEG_4`. So it could be that your device is selecting `H263` as it's default encoder and `MPEG_4` for the format, which might be causing the issue.

I tried default settings but error.

**Comment by sutanurath** [comment] 2020-10-05 10:28
This is error log after set default

 E/HBRecorderOnError: 268435556
2020-10-05 15:56:55.257 429-429/? E/hwcomposer: [HWC] (2) handle of outbuf missing  
2020-10-05 15:56:55.258 429-429/? E/hwcomposer: [HWC] (2) handle of outbuf missing  
2020-10-05 15:56:55.259 443-443/? E/SurfaceFlinger: [ScreenRecordService] advanceFrame: no buffer, bailing out
2020-10-05 15:56:55.259 443-443/? E/DisplayDevice: [ScreenRecordService] failed pushing new frame to HWC: -12
2020-10-05 15:56:55.271 583-13580/? E/BufferQueueProducer: [GraphicBufferSource](this:0xe93f5000,id:4,api:1,p:583,c:-1) dequeueBuffer: BufferQueue has been abandoned
2020-10-05 15:56:55.271 583-13580/? E//vendor/bin/hw/android.hardware.media.omx@1.0-service: TWGraphicBufferProducer::dequeueBuffer - Invalid output fence

**Comment by sutanurath** [comment] 2020-10-05 10:41
> 
> 
> If that also doesn't work, run the following and let me know what it returns:
> 
> ```java
> public void logAvailableVideoEncoders(){
>     final int numCodecs = MediaCodecList.getCodecCount();
>     for (int i = 0; i < numCodecs; i++) {
>         final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
>         if (!codecInfo.isEncoder()) { 
>             continue;
>         }
>         final String[] types = codecInfo.getSupportedTypes();
>         for (int j = 0; j < types.length; j++) {
>             if (types[j].contains("video")){
>                 Log.e("Available Encoders", codecInfo.getName());
>             }
>         }
>     }
> }
> ```

numCodecs = 65

System.out: Available Encoders=OMX.MTK.VIDEO.ENCODER.AVC
System.out: Available Encoders=OMX.google.h264.encoder
Available Encoders=OMX.MTK.VIDEO.ENCODER.H263
OMX.google.h263.encoder
OMX.MTK.VIDEO.ENCODER.HEVC
OMX.MTK.VIDEO.ENCODER.MPEG4
OMX.google.mpeg4.encoder
OMX.google.vp8.encoder

**Comment by alexrad89** [comment] 2020-10-10 15:45
@sutanurath can you post the settings code you used im also getting this error.

**Comment by alexrad89** [comment] 2020-10-10 15:59
![image](https://user-images.githubusercontent.com/4390213/95659578-95b01480-0ae7-11eb-90e0-ed3f924dba4d.png)
This is what i used and same error.

**Comment by HBiSoft** [comment] 2020-10-17 13:54
If any of you have the time, please update `HBRecorderCodecInfo.java` to the following:

```java
package com.hbisoft.hbrecorder;

import android.content.Context;
import android.content.res.Configuration;
import android.media.CamcorderProfile;
import android.media.MediaCodecInfo;
import android.media.MediaCodecList;
import android.os.Build;
import android.util.DisplayMetrics;
import android.util.Range;
import android.view.WindowManager;

import androidx.annotation.RequiresApi;

import java.util.ArrayList;
import java.util.HashMap;

import static android.content.Context.WINDOW_SERVICE;
import static android.content.res.Configuration.ORIENTATION_LANDSCAPE;
import static android.content.res.Configuration.ORIENTATION_PORTRAIT;

/**
 * Created by HBiSoft on 13 Aug 2019
 * Copyright (c) 2019 . All rights reserved.
 */

public class HBRecorderCodecInfo {

    int getMaxSupportedWidth(){
        RecordingInfo recordingInfo = getRecordingInfo();
        return recordingInfo.width;
    }

    int getMaxSupportedHeight(){
        RecordingInfo recordingInfo = getRecordingInfo();
        return recordingInfo.height;
    }

    private RecordingInfo getRecordingInfo() {
        DisplayMetrics displayMetrics = new DisplayMetrics();
        WindowManager wm = (WindowManager) context.getSystemService(WINDOW_SERVICE);
        wm.getDefaultDisplay().getRealMetrics(displayMetrics);
        int displayWidth = displayMetrics.widthPixels;
        int displayHeight = displayMetrics.heightPixels;
        int displayDensity = displayMetrics.densityDpi;

        Configuration configuration = context.getResources().getConfiguration();
        boolean isLandscape = configuration.orientation == ORIENTATION_LANDSCAPE;

        CamcorderProfile camcorderProfile = CamcorderProfile.get(CamcorderProfile.QUALITY_HIGH);
        int cameraWidth = camcorderProfile != null ? camcorderProfile.videoFrameWidth : -1;
        int cameraHeight = camcorderProfile != null ? camcorderProfile.videoFrameHeight : -1;
        int cameraFrameRate = camcorderProfile != null ? camcorderProfile.videoFrameRate : 30;


        return calculateRecordingInfo(displayWidth, displayHeight, displayDensity, isLandscape,
                cameraWidth, cameraHeight, cameraFrameRate, 100);
    }

    private Context context;

    public void setContext(Context c) {
        context = c;
    }

    static final class RecordingInfo {
        final int width;
        final int height;
        final int frameRate;
        final int density;

        RecordingInfo(int width, int height, int frameRate, int density) {
            this.width = width;
            this.height = height;
            this.frameRate = frameRate;
            this.density = density;
        }
    }

    static RecordingInfo calculateRecordingInfo(int displayWidth, int displayHeight, int displayDensity, boolean isLandscapeDevice, int cameraWidth, int cameraHeight, int cameraFrameRate, int sizePercentage) {
        // Scale the display size before any maximum size calculations.
        displayWidth = displayWidth * sizePercentage / 100;
        displayHeight = displayHeight * sizePercentage / 100;

        if (cameraWidth == -1 && cameraHeight == -1) {
            // No cameras. Fall back to the display size.
            return new RecordingInfo(displayWidth, displayHeight, cameraFrameRate, displayDensity);
        }

        int frameWidth = isLandscapeDevice ? cameraWidth : cameraHeight;
        int frameHeight = isLandscapeDevice ? cameraHeight : cameraWidth;
        if (frameWidth >= displayWidth && frameHeight >= displayHeight) {
            // Frame can hold the entire display. Use exact values.
            return new RecordingInfo(displayWidth, displayHeight, cameraFrameRate, displayDensity);
        }

        // Calculate new width or height to preserve aspect ratio.
        if (isLandscapeDevice) {
            frameWidth = displayWidth * frameHeight / displayHeight;
        } else {
            frameHeight = displayHeight * frameWidth / displayWidth;
        }
        return new RecordingInfo(frameWidth, frameHeight, cameraFrameRate, displayDensity);
    }


    // ALL PUBLIC METHODS

    // Select the default video encoder
    // This will only return the default video encoder, it does not mean that the encoder supports a particular set of parameters
    public final MediaCodecInfo selectVideoCodec(final String mimeType) {
        MediaCodecInfo result = null;
        // get the list of available codecs
        final int numCodecs = MediaCodecList.getCodecCount();
        for (int i = 0; i < numCodecs; i++) {
            final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
            if (!codecInfo.isEncoder()) {    // skipp decoder
                continue;
            }
            final String[] types = codecInfo.getSupportedTypes();
            for (int j = 0; j < types.length; j++) {
                if (types[j].contains("video")){
                    return codecInfo;
                }
            }
        }
        return result;
    }

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    private MediaCodecInfo selectDefaultCodec(int width, int height) {
        MediaCodecInfo result = null;
        // get the list of available codecs
        final int numCodecs = MediaCodecList.getCodecCount();
        for (int i = 0; i < numCodecs; i++) {
            final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
            if (!codecInfo.isEncoder()) {    // skipp decoder
                continue;
            }
            final String[] types = codecInfo.getSupportedTypes();
            for (int j = 0; j < types.length; j++) {
                if (types[j].contains("video")){
                    MediaCodecInfo.CodecCapabilities codecCapabilities = codecInfo.getCapabilitiesForType(types[j]);
                    boolean formatSup = codecCapabilities.isFormatSupported(codecCapabilities.getDefaultFormat());
                    if (formatSup) {
                        return codecInfo;
                    }
                }
            }
        }
        return result;
    }

    // Get the default video encoder name
    // The default one will be returned first
    public String getDefaultVideoEncoder(String mimeType){
        String defaultEncoder = "";
        try {
            final MediaCodecInfo codecInfo = selectVideoCodec(mimeType);
            String[] types = codecInfo.getSupportedTypes();
            for (String type : types) {
                if (type.contains("video")) {
                    return codecInfo.getName();
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return defaultEncoder;
    }

    // Get the default video format
    // The default one will be returned first
    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public String getDefaultVideoFormat(HBRecorder hbRecorder){
        String supported = "";
        try {
            final MediaCodecInfo codecInfo = selectDefaultCodec(hbRecorder.getDefaultWidth(), hbRecorder.getDefaultHeight());
            String[] types = codecInfo.getSupportedTypes();
            for (String type : types) {
                if (type.contains("video")) {
                    MediaCodecInfo.CodecCapabilities codecCapabilities = codecInfo.getCapabilitiesForType(type);
                    String result = codecCapabilities.getDefaultFormat().toString();
                    return returnTypeFromMime(result.substring(result.indexOf("=") + 1, result.indexOf(",")));
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return supported;
    }

    private String returnTypeFromMime(String mimeType){
        switch (mimeType) {
            case "video/MP2T":
                return "MPEG_2_TS";
            case "video/mp4v-es":
                return "MPEG_4";
            case "video/mp4v":
                return "MPEG_4";
            case "video/mp4":
                return "MPEG_4";
            case "video/avc":
                return "MPEG_4";
            case "video/3gpp":
                return "THREE_GPP";
            case "video/webm":
                return "WEBM";
            case "video/video/x-vnd.on2.vp8":
                return "WEBM";
        }
        return "";
    }

    // Example usage - isSizeAndFramerateSupported(hbrecorder.getWidth(), hbrecorder.getHeight(), 30, "video/mp4", ORIENTATION_PORTRAIT);
    // int width - The width of the view to be recorder
    // int height - The height of the view to be recorder
    // String mimeType - for ex. video/mp4
    // int orientation - ORIENTATION_PORTRAIT or ORIENTATION_LANDSCAPE
    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public boolean isSizeAndFramerateSupported(int width, int height, int fps, String mimeType, int orientation){
        boolean supported = false;
        try {
            final MediaCodecInfo codecInfo = selectVideoCodec(mimeType);
            String[] types = codecInfo.getSupportedTypes();
            for (String type : types) {
                if (type.contains("video")) {
                    MediaCodecInfo.CodecCapabilities codecCapabilities = codecInfo.getCapabilitiesForType(type);
                    MediaCodecInfo.VideoCapabilities videoCapabilities = codecCapabilities.getVideoCapabilities();
                    //Range<Double> bit = videoCapabilities.isSizeSupported()
                   // Log.e("fram", " "+isSizeSupported(width, height, mimeType));

                    // Flip around the width and height in ORIENTATION_PORTRAIT because android's default orientation is ORIENTATION_LANDSCAPE
                    if (ORIENTATION_PORTRAIT == orientation) {
                        supported = videoCapabilities.areSizeAndRateSupported(height, width, fps);
                    }else {
                        supported = videoCapabilities.areSizeAndRateSupported(width, height, fps);
                    }
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return supported;
    }

    // Check if a particular size is supported
    // Provide width and height in Portrait mode, for example. isSizeSupported(1080, 1920, "video/mp4");
    // We do this because android's default orientation is landscape, so we have to flip around the width and height
    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public boolean isSizeSupported(int width, int height, String mimeType){
        boolean supported = false;
        try {
            final MediaCodecInfo codecInfo = selectVideoCodec(mimeType);
            String[] types = codecInfo.getSupportedTypes();
            for (String type : types) {
                if (type.contains("video")) {
                    MediaCodecInfo.CodecCapabilities codecCapabilities = codecInfo.getCapabilitiesForType(type);
                    MediaCodecInfo.VideoCapabilities videoCapabilities = codecCapabilities.getVideoCapabilities();
                    supported = videoCapabilities.isSizeSupported(height, width);
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return supported;
    }

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public double getMaxSupportedFrameRate(int width, int height, String mimeType){
        double maxFPS = 0;
        try {
            final MediaCodecInfo codecInfo = selectVideoCodec(mimeType);
            String[] types = codecInfo.getSupportedTypes();
            for (String type : types) {
                if (type.contains("video")) {
                    MediaCodecInfo.CodecCapabilities codecCapabilities = codecInfo.getCapabilitiesForType(type);
                    MediaCodecInfo.VideoCapabilities videoCapabilities = codecCapabilities.getVideoCapabilities();
                    Range<Double> bit = videoCapabilities.getSupportedFrameRatesFor(height, width);
                    maxFPS = bit.getUpper();
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return maxFPS;
    }

    // Get the max supported bitrate for a particular mime type
    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public int getMaxSupportedBitrate(String mimeType){
        int bitrate = 0;
        try {
            final MediaCodecInfo codecInfo = selectVideoCodec(mimeType);
            String[] types = codecInfo.getSupportedTypes();
            for (String type : types) {
                if (type.contains("video")) {
                    MediaCodecInfo.CodecCapabilities codecCapabilities = codecInfo.getCapabilitiesForType(type);
                    MediaCodecInfo.VideoCapabilities videoCapabilities = codecCapabilities.getVideoCapabilities();
                    Range<Integer> bit = videoCapabilities.getBitrateRange();

                    bitrate = bit.getUpper();

                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return bitrate;
    }

    // Get supported video formats
    ArrayList<String> supportedVideoFormats = new ArrayList<>();
    public ArrayList<String> getSupportedVideoFormats(){
        String[] allFormats = {"video/MP2T", "video/mp4v-es", "video/m4v", "video/mp4", "video/avc", "video/3gpp", "video/webm", "video/x-vnd.on2.vp8"};

        for (String allFormat : allFormats) {
            checkSupportedVideoFormats(allFormat);
        }
        return supportedVideoFormats;
    }
    private void checkSupportedVideoFormats(String mimeType){
        // get the list of available codecs
        final int numCodecs = MediaCodecList.getCodecCount();
        LOOP:
        for (int i = 0; i < numCodecs; i++) {
            final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
            if (!codecInfo.isEncoder()) {    // skipp decoder
                continue;
            }
            final String[] types = codecInfo.getSupportedTypes();
            label:
            for (int j = 0; j < types.length; j++) {
                if (types[j].contains("video")){
                    switch (mimeType) {
                        case "video/MP2T":
                            supportedVideoFormats.add("MPEG_2_TS");
                            break LOOP;
                        case "video/mp4v-es":
                            if(!supportedVideoFormats.contains("MPEG_4")) {
                                supportedVideoFormats.add("MPEG_4");
                            }
                            break LOOP;
                        case "video/mp4v":
                            if(!supportedVideoFormats.contains("MPEG_4")) {
                                supportedVideoFormats.add("MPEG_4");
                            }
                            break LOOP;
                        case "video/mp4":
                            if(!supportedVideoFormats.contains("MPEG_4")) {
                                supportedVideoFormats.add("MPEG_4");
                            }
                            break LOOP;
                        case "video/avc":
                            if(!supportedVideoFormats.contains("MPEG_4")) {
                                supportedVideoFormats.add("MPEG_4");
                            }
                            break LOOP;
                        case "video/3gpp":
                            supportedVideoFormats.add("THREE_GPP");
                            break LOOP;

                        case "video/webm":
                            if(!supportedVideoFormats.contains("WEBM")) {
                                supportedVideoFormats.add("WEBM");
                            }
                            break LOOP;
                        case "video/video/x-vnd.on2.vp8":
                            if(!supportedVideoFormats.contains("WEBM")) {
                                supportedVideoFormats.add("WEBM");
                            }
                            break LOOP;

                    }
                }
            }
        }
    }

    // Get supported audio formats
    ArrayList<String> supportedAudioFormats = new ArrayList<>();
    public ArrayList<String> getSupportedAudioFormats(){
        String[] allFormats = {"audio/amr_nb", "audio/amr_wb", "audio/x-hx-aac-adts", "audio/ogg"};

        for (String allFormat : allFormats) {
            checkSupportedAudioFormats(allFormat);
        }
        return supportedAudioFormats;
    }
    private void checkSupportedAudioFormats(String mimeType){
        // get the list of available codecs
        final int numCodecs = MediaCodecList.getCodecCount();
        LOOP:
        for (int i = 0; i < numCodecs; i++) {
            final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
            if (!codecInfo.isEncoder()) {    // skipp decoder
                continue;
            }
            final String[] types = codecInfo.getSupportedTypes();
            label:
            for (int j = 0; j < types.length; j++) {
                if (types[j].contains("audio")){
                    switch (mimeType) {
                        case "audio/amr_nb":
                            supportedAudioFormats.add("AMR_NB");
                            break LOOP;
                        case "audio/amr_wb":
                            supportedAudioFormats.add("AMR_WB");
                            break LOOP;
                        case "audio/x-hx-aac-adts":
                            supportedAudioFormats.add("AAC_ADTS");
                            break LOOP;
                        case "audio/ogg":
                            supportedAudioFormats.add("OGG");
                            break LOOP;
                    }
                }
            }
        }
    }

    // Get supported video mime types
    HashMap<String, String> mVideoMap= new HashMap<>();
    public HashMap<String, String> getSupportedVideoMimeTypes(){
        checkIfSupportedVideoMimeTypes();
        return mVideoMap;
    }
    private void checkIfSupportedVideoMimeTypes(){
        // get the list of available codecs
        final int numCodecs = MediaCodecList.getCodecCount();
        for (int i = 0; i < numCodecs; i++) {
            final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
            if (!codecInfo.isEncoder()) {    // skipp decoder
                continue;
            }
            final String[] types = codecInfo.getSupportedTypes();
            for (String type : types) {
                if (type.contains("video")) {
                    mVideoMap.put(codecInfo.getName(), type);
                }
            }
        }
    }

    // Get supported audio mime types
    HashMap<String, String> mAudioMap= new HashMap<>();
    public HashMap<String, String> getSupportedAudioMimeTypes(){
        checkIfSupportedAudioMimeTypes();
        return mAudioMap;
    }
    private void checkIfSupportedAudioMimeTypes(){
        // get the list of available codecs
        final int numCodecs = MediaCodecList.getCodecCount();
        for (int i = 0; i < numCodecs; i++) {
            final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
            if (!codecInfo.isEncoder()) {    // skipp decoder
                continue;
            }
            final String[] types = codecInfo.getSupportedTypes();
            for (String type : types) {
                if (type.contains("audio")) {
                    mAudioMap.put(codecInfo.getName(), type);
                }
            }
        }
    }

}
```

Then in `MainActivity` (After calling `hbRecorder = new HBRecorder(this, this);`), add the following:

```java
// Examples of how to use the HBRecorderCodecInfo class to get codec info
HBRecorderCodecInfo hbRecorderCodecInfo = new HBRecorderCodecInfo();
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
    int mWidth = hbRecorder.getDefaultWidth();
    int mHeight = hbRecorder.getDefaultHeight();
    String mMimeType = "video/3gpp";
    int mFPS = 30;
    String defaultVideoEncoder = hbRecorderCodecInfo.getDefaultVideoEncoder(mMimeType);
    boolean isSizeAndFramerateSupported = hbRecorderCodecInfo.isSizeAndFramerateSupported(mWidth, mHeight, mFPS, mMimeType, ORIENTATION_PORTRAIT);

    Log.e("EXAMPLE", "THIS IS AN EXAMPLE OF HOW TO USE THE (HBRecorderCodecInfo) TO GET CODEC INFO:");
    Log.e("HBRecorderCodecInfo","defaultVideoEncoder for ("+mMimeType+") -> "+defaultVideoEncoder);
    Log.e("HBRecorderCodecInfo", "MaxSupportedFrameRate -> "+hbRecorderCodecInfo.getMaxSupportedFrameRate(mWidth, mHeight, mMimeType));
    Log.e("HBRecorderCodecInfo", "MaxSupportedBitrate -> "+hbRecorderCodecInfo.getMaxSupportedBitrate(mMimeType));
    Log.e("HBRecorderCodecInfo","isSizeAndFramerateSupported -> "+ isSizeAndFramerateSupported);
    Log.e("HBRecorderCodecInfo", "isSizeSupported -> "+hbRecorderCodecInfo.isSizeSupported(mWidth, mHeight, mMimeType));
    Log.e("HBRecorderCodecInfo", "Default Video Format = "+hbRecorderCodecInfo.getDefaultVideoFormat(hbRecorder));

    HashMap<String, String> supportedVideoMimeTypes = hbRecorderCodecInfo.getSupportedVideoMimeTypes();
    for (Map.Entry<String,String> entry : supportedVideoMimeTypes.entrySet()) {
        Log.e("HBRecorderCodecInfo", "Supported VIDEO encoders and mime types : "+entry.getKey()+" -> "+entry.getValue());
    }

    HashMap<String, String> supportedAudioMimeTypes = hbRecorderCodecInfo.getSupportedAudioMimeTypes();
    for (Map.Entry<String,String> entry : supportedAudioMimeTypes.entrySet()) {
        Log.e("HBRecorderCodecInfo", "Supported AUDIO encoders and mime types : "+entry.getKey()+" -> "+entry.getValue());
    }

    ArrayList<String> supportedVideoFormats = hbRecorderCodecInfo.getSupportedVideoFormats();
    for (int j = 0; j < supportedVideoFormats.size(); j++) {
        Log.e("HBRecorderCodecInfo", "Available Video Formats : "+supportedVideoFormats.get(j));
    }

}
```
Then provide me with the log.

**Comment by HBiSoft** [comment] 2020-10-20 06:48
I have updated the library and it will now return the above information when running the application.

I need one of you to run the updated application and provide me with the log, it will look something like this:

```log
E/HBRecorderCodecInfo: defaultVideoEncoder for (video/avc) -> OMX.Exynos.AVC.Encoder
E/HBRecorderCodecInfo: MaxSupportedFrameRate -> 59.55882352941177
E/HBRecorderCodecInfo: MaxSupportedBitrate -> 40000000
E/HBRecorderCodecInfo: isSizeAndFramerateSupported @ Width = 1080 Height = +1920 FPS = 30 -> true
E/HBRecorderCodecInfo: isSizeSupported @ Width = 1080 Height = +1920 -> true
E/HBRecorderCodecInfo: Default Video Format = MPEG_4
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.mpeg4.encoder -> video/mp4v-es
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.h264.encoder -> video/avc
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.Exynos.HEVC.Encoder -> video/hevc
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.Exynos.H263.Encoder -> video/3gpp
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.vp8.encoder -> video/x-vnd.on2.vp8
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.google.h263.encoder -> video/3gpp
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.Exynos.AVC.Encoder -> video/avc
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.Exynos.MPEG4.Encoder -> video/mp4v-es
E/HBRecorderCodecInfo: Supported VIDEO encoders and mime types : OMX.Exynos.VP8.Encoder -> video/x-vnd.on2.vp8
E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.amrnb.encoder -> audio/3gpp
E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.amrwb.encoder -> audio/amr-wb
E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.SEC.naac.enc -> audio/mp4a-latm
E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.aac.encoder -> audio/mp4a-latm
E/HBRecorderCodecInfo: Supported AUDIO encoders and mime types : OMX.google.flac.encoder -> audio/flac
E/HBRecorderCodecInfo: Available Video Formats : MPEG_2_TS
E/HBRecorderCodecInfo: Available Video Formats : MPEG_4
E/HBRecorderCodecInfo: Available Video Formats : THREE_GPP
E/HBRecorderCodecInfo: Available Video Formats : WEBM
```

**Comment by HBiSoft** [comment] 2020-10-29 01:29
I really wanted to know the cause behind this issue, but unfortunately did not get a reply. I will be closing this issue for now.

<b>I future readers has the same issue, please run the demo application and provide me with the log mentioned in the previous comment.</b>

**Closed by HBiSoft** 2020-10-29 01:29 UTC
Labels: Need more info

**Comment by aruproy** [comment] 2020-11-17 20:47
@HBiSoft Thank you for this great library. I have just added the issue #43 
I really need to get this issue fixed. How do I get the latest update of the library? I will provide you all details that you need.
